/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressStorage } from "./AddressStorage";
export type { ISyntheX } from "./ISyntheX";
export type { SyntheX } from "./SyntheX";
export type { SyntheXStorage } from "./SyntheXStorage";
