/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPeripheryContractSol from "./MockPeripheryContract.sol";
export type { mockPeripheryContractSol };
import type * as selfDestructTransferSol from "./SelfDestructTransfer.sol";
export type { selfDestructTransferSol };
export type { MockIncentivesController } from "./MockIncentivesController";
export type { MockReserveConfiguration } from "./MockReserveConfiguration";
