/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { IGovernancePowerDelegationToken__factory } from "./IGovernancePowerDelegationToken__factory";
